use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target "H1BJobs" do
    pod 'Google/Analytics'
	pod "SQLite.swift",
  		git: "https://github.com/stephencelis/SQLite.swift",
  		branch: "cocoapods-xcode-7-3"
end