use_frameworks!

pod 'SQLite.swift',
  git: 'https://github.com/stephencelis/SQLite.swift.git'

# instead, for SQLCipher support
pod 'SQLiteCipher.swift',
  git: 'https://github.com/stephencelis/SQLite.swift.git'