use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'SQLite.swift',
  git: 'https://github.com/stephencelis/SQLite.swift.git'

# instead, for SQLCipher support
pod 'SQLiteCipher.swift',
  git: 'https://github.com/stephencelis/SQLite.swift.git'